### ISSUE TITLE
variable push force

### ISSUE THREAD

**Issue by McDiod** [veteran29/vet_unflipping#19]
There are cases where the [calculated push force](https://github.com/veteran29/vet_unflipping/blob/master/addons/unflipping/functions/fn_unflipVehicle.sqf#L38) does not completely flip the vehicle.

There are multiple ways of solving this:

1. After unflipping, check if vehicle is still upside down. If so, next unflip attempt will use more force.
2. Add child actions to unflip node allowing the user to select 80%/90%/100%/110%/120% force. (What happens if users select different forces on the same attempt?)
3. Calculate force based on unflipping users. If 3 users are required for a vehicle, 2 users will not work, 3 users will apply 100% force, 4 users will apply 110% force, etc.

Opinions?

**Comment by veteran29** [comment]
Yeah it's not 100% reliable right now. 

The physics engine is kinda strange... with some vehicles I was able to consistently reporoduce following:
```
1. Try to unflip
2. Vehicle stays floating on 2 wheels for a moment
3. Vehicle falls in initial position
4. Wait 10s to let it settle to initial position
5. Repeat
6. After Nth try it unflips fully despite having the same tilt as initially ¯\_(ツ)_/¯
```

Personally I see 1st option as most sensible one.
