### ISSUE TITLE
timer + new xml rus

### ISSUE THREAD

**Issue by topden** [veteran29/vet_unflipping#7]
http://joxi.ru/8AnbE8qTzjwoRA
http://joxi.ru/5mdBgRqC3kYqkA
Could you increase the flip timer to 300 seconds. In some game modes such as pvp, players need more time for a coup. I think 5 minutes is the maximum for the game and hardcore

new xml rus  https://drive.google.com/open?id=1FarJHAaFN7M49r4FppKlEGEKlPWCAbW9

**Comment by veteran29** [comment]
Unfortunately current implementation does not allow to cancel unflipping, so if you would set it to 5mins you would be stuck for 5 mins looking at progressbar.

I could increase slider value after adding #9

**Comment by topden** [comment]
ok.thx
